MvcBasic_Clone/Controllers/FormController.cs
using MvcBasic_Clone.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FormContext = MvcBasic_Clone.Models.FormContext;

namespace MvcBasic_Clone.Controllers
{
    public class FormController : Controller
    {
        private FormContext db = new FormContext();
        private FriendContext frienddb = new FriendContext();
        // GET: Form
        public ActionResult Index()
        {
            return View(db.Infoes.ToList());
        }

        public ActionResult Indexfriend()
        {
            return View(frienddb.Employees.ToList());
        }
        // GET: Friends/Create
        public ActionResult UserInfo()
        {
            return View();
        }


        // POST: Friends/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserInfo([Bind(Include = "Id,Name,Phone,Email,Gender")] Info input)
        {
            if (ModelState.IsValid)
            {
                db.Infoes.Add(input);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserData(string name,string phone,string email,string gender)
        {
            Info info = new Info { Name = name, Phone = phone, Email = email, Gender = gender };

            db.Infoes.Add(info);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcBasic_Clone/Views/Form/Index.cshtml
@model IEnumerable<MvcBasic_Clone.Models.Info>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MvcBasic_Clone/Views/Form/Indexfriend.cshtml
@model IEnumerable<MvcBasic_Clone.Models.Employee>

@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

@section endJS{
    <script>
        function GetName() {
            console.log("endtopJS");
        }

        GetName();
    </script>
}

@section endCSS{
    <style>
        body {
            background-color: rosybrown
        }
    </style>
}

@section topJS{
    <script>
        function GetName() {
            console.log("topJS");
        }

        GetName();
    </script>
}


@section topCSS{
    <style>
        td:hover {
            background-color: lightcyan
        }
    </style>
}

MvcBasic_Clone/Views/Form/UserInfo.cshtml
@model Info

@{
    ViewBag.Title = "UserInfo";
}

<h2>Lexus賞車活動</h2>

@using (Html.BeginForm("UserData", "Form"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Info</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "請輸入姓名" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = "請輸入電話" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-info" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "請輸入性別" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



@section topJS{
    <script>
        function GetName() {
            console.log("topJS");
        }

        GetName();
    </script>
}


@section topCSS{
    <style>
        input:hover {
            background-color: lightblue
        }
    </style>
}

@section endJS{
    <script>
        function GetName() {
            console.log("endtopJS");
        }

        GetName();
    </script>
}

@section endCSS{
    <style>
        body {
            background-color: lightgoldenrodyellow
        }
    </style>
}